package net.minecraft.client.gui;

import com.google.common.collect.Lists;
import com.google.common.util.concurrent.Runnables;
import net.minecraft.client.Minecraft;
import net.minecraft.client.renderer.BufferBuilder;
import net.minecraft.client.renderer.GlStateManager;
import net.minecraft.client.renderer.OpenGlHelper;
import net.minecraft.client.renderer.Tessellator;
import net.minecraft.client.renderer.texture.DynamicTexture;
import net.minecraft.client.renderer.vertex.DefaultVertexFormats;
import net.minecraft.client.resources.I18n;
import net.minecraft.client.resources.IResource;
import net.minecraft.client.settings.GameSettings;
import net.minecraft.realms.RealmsBridge;
import net.minecraft.util.ResourceLocation;
import net.minecraft.util.StringUtils;
import net.minecraft.util.math.MathHelper;
import net.minecraft.util.text.TextFormatting;
import net.minecraft.world.WorldServerDemo;
import net.minecraft.world.storage.ISaveFormat;
import net.minecraft.world.storage.WorldInfo;
import org.apache.commons.io.IOUtils;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.lwjgl.input.Mouse;
import org.lwjgl.opengl.GLContext;
import org.lwjgl.util.glu.Project;

import java.io.BufferedReader;
import java.io.Closeable;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.URI;
import java.nio.charset.StandardCharsets;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.Random;

public class GuiMainMenu extends GuiScreen {

	private static final Logger LOGGER = LogManager.getLogger();
	private static final Random RANDOM = new Random();

	/**
	 * A random number between 0.0 and 1.0, used to determine if the title screen says <a
	 * href="https://minecraft.gamepedia.com/Menu_screen#Minceraft">Minceraft</a> instead of Minecraft. Set during
	 * construction; if the value is less than .0001, then Minceraft is displayed.
	 */
	private final float minceraftRoll;

	/**
	 * The splash message.
	 */
	private String splashText;
	private GuiButton buttonResetDemo;

	/**
	 * Timer used to rotate the panorama, increases every tick.
	 */
	private float panoramaTimer;

	/**
	 * Texture allocated for the current viewport of the main menu's panorama background.
	 */
	private DynamicTexture viewportTexture;

	/**
	 * The Object object utilized as a thread lock when performing non thread-safe operations
	 */
	private final Object threadLock = new Object();
	public static final String MORE_INFO_TEXT = "Please click " + TextFormatting.UNDERLINE + "here" + TextFormatting.RESET + " for more information.";

	/**
	 * Width of openGLWarning2
	 */
	private int openGLWarning2Width;

	/**
	 * Width of openGLWarning1
	 */
	private int openGLWarning1Width;

	/**
	 * Left x coordinate of the OpenGL warning
	 */
	private int openGLWarningX1;

	/**
	 * Top y coordinate of the OpenGL warning
	 */
	private int openGLWarningY1;

	/**
	 * Right x coordinate of the OpenGL warning
	 */
	private int openGLWarningX2;

	/**
	 * Bottom y coordinate of the OpenGL warning
	 */
	private int openGLWarningY2;

	/**
	 * OpenGL graphics card warning.
	 */
	private String openGLWarning1;

	/**
	 * OpenGL graphics card warning.
	 */
	private String openGLWarning2;

	/**
	 * Link to the Mojang Support about minimum requirements
	 */
	private String openGLWarningLink;
	private static final ResourceLocation SPLASH_TEXTS = new ResourceLocation("texts/splashes.txt");
	private static final ResourceLocation MINECRAFT_TITLE_TEXTURES = new ResourceLocation("textures/gui/title/minecraft.png");
	private static final ResourceLocation field_194400_H = new ResourceLocation("textures/gui/title/edition.png");

	/**
	 * An array of all the paths to the panorama pictures.
	 */
	private static final ResourceLocation[] TITLE_PANORAMA_PATHS = new ResourceLocation[]{new ResourceLocation("textures/gui/title/background/panorama_0.png"), new ResourceLocation("textures/gui/title/background/panorama_1.png"), new ResourceLocation("textures/gui/title/background/panorama_2.png"), new ResourceLocation("textures/gui/title/background/panorama_3.png"), new ResourceLocation("textures/gui/title/background/panorama_4.png"), new ResourceLocation("textures/gui/title/background/panorama_5.png")};
	private ResourceLocation backgroundTexture;

	/**
	 * Minecraft Realms button.
	 */
	private GuiButton realmsButton;

	/**
	 * Has the check for a realms notification screen been performed?
	 */
	private boolean hasCheckedForRealmsNotification;

	/**
	 * A screen generated by realms for notifications; drawn in adition to the main menu (buttons and such from both are
	 * drawn at the same time). May be null.
	 */
	private GuiScreen realmsNotification;
	private int widthCopyright;
	private int widthCopyrightRest;

	public GuiMainMenu() {

		openGLWarning2 = MORE_INFO_TEXT;
		splashText = "missingno";
		IResource iresource = null;

		try {
			List<String> list = Lists.newArrayList();
			iresource = Minecraft.getMinecraft().getResourceManager().getResource(SPLASH_TEXTS);
			BufferedReader bufferedreader = new BufferedReader(new InputStreamReader(iresource.getInputStream(), StandardCharsets.UTF_8));
			String s;

			while ((s = bufferedreader.readLine()) != null) {
				s = s.trim();

				if (!s.isEmpty()) {
					list.add(s);
				}
			}

			if (!list.isEmpty()) {
				while (true) {
					splashText = list.get(RANDOM.nextInt(list.size()));

					if (splashText.hashCode() != 125780783) {
						break;
					}
				}
			}
		} catch (IOException var8) {
		} finally {
			IOUtils.closeQuietly(iresource);
		}

		minceraftRoll = RANDOM.nextFloat();
		openGLWarning1 = "";

		if (!GLContext.getCapabilities().OpenGL20 && !OpenGlHelper.areShadersSupported()) {
			openGLWarning1 = I18n.format("title.oldgl1");
			openGLWarning2 = I18n.format("title.oldgl2");
			openGLWarningLink = "https://help.mojang.com/customer/portal/articles/325948?ref=game";
		}
	}

	/**
	 * Is there currently a realms notification screen, and are realms notifications enabled?
	 */
	private boolean areRealmsNotificationsEnabled() {

		return Minecraft.getMinecraft().gameSettings.getOptionOrdinalValue(GameSettings.Options.REALMS_NOTIFICATIONS) && realmsNotification != null;
	}

	/**
	 * Called from the main game loop to update the screen.
	 */
	public void updateScreen() {

		if (areRealmsNotificationsEnabled()) {
			realmsNotification.updateScreen();
		}
	}

	/**
	 * Returns true if this GUI should pause the game when it is displayed in single-player
	 */
	public boolean doesGuiPauseGame() {

		return false;
	}

	/**
	 * Fired when a key is typed (except F11 which toggles full screen). This is the equivalent of
	 * KeyListener.keyTyped(KeyEvent e). Args : character (character on the key), keyCode (lwjgl Keyboard key code)
	 */
	protected void keyTyped(char typedChar, int keyCode) throws IOException {

	}

	/**
	 * Adds the buttons (and other controls) to the screen in question. Called when the GUI is displayed and when the
	 * window resizes, the buttonList is cleared beforehand.
	 */
	public void initGui() {

		viewportTexture = new DynamicTexture(256, 256);
		backgroundTexture = mc.getTextureManager().getDynamicTextureLocation("background", viewportTexture);
		widthCopyright = fontRenderer.getStringWidth("Copyright Mojang AB. Do not distribute!");
		widthCopyrightRest = width - widthCopyright - 2;
		Calendar calendar = Calendar.getInstance();
		calendar.setTime(new Date());

		if (calendar.get(2) + 1 == 12 && calendar.get(5) == 24) {
			splashText = "Merry X-mas!";
		} else if (calendar.get(2) + 1 == 1 && calendar.get(5) == 1) {
			splashText = "Happy new year!";
		} else if (calendar.get(2) + 1 == 10 && calendar.get(5) == 31) {
			splashText = "OOoooOOOoooo! Spooky!";
		}

		int i = 24;
		int j = height / 4 + 48;

		if (mc.isDemo()) {
			addDemoButtons(j, 24);
		} else {
			addSingleplayerMultiplayerButtons(j, 24);
		}

		buttonList.add(new GuiButton(0, width / 2 - 100, j + 72 + 12, 98, 20, I18n.format("menu.options")));
		buttonList.add(new GuiButton(4, width / 2 + 2, j + 72 + 12, 98, 20, I18n.format("menu.quit")));
		buttonList.add(new GuiButtonLanguage(5, width / 2 - 124, j + 72 + 12));

		synchronized (threadLock) {
			openGLWarning1Width = fontRenderer.getStringWidth(openGLWarning1);
			openGLWarning2Width = fontRenderer.getStringWidth(openGLWarning2);
			int k = Math.max(openGLWarning1Width, openGLWarning2Width);
			openGLWarningX1 = (width - k) / 2;
			openGLWarningY1 = (buttonList.get(0)).y - 24;
			openGLWarningX2 = openGLWarningX1 + k;
			openGLWarningY2 = openGLWarningY1 + 24;
		}

		mc.setConnectedToRealms(false);

		if (Minecraft.getMinecraft().gameSettings.getOptionOrdinalValue(GameSettings.Options.REALMS_NOTIFICATIONS) && !hasCheckedForRealmsNotification) {
			RealmsBridge realmsbridge = new RealmsBridge();
			realmsNotification = realmsbridge.getNotificationScreen(this);
			hasCheckedForRealmsNotification = true;
		}

		if (areRealmsNotificationsEnabled()) {
			realmsNotification.setGuiSize(width, height);
			realmsNotification.initGui();
		}
	}

	/**
	 * Adds Singleplayer and Multiplayer buttons on Main Menu for players who have bought the game.
	 */
	private void addSingleplayerMultiplayerButtons(int p_73969_1_, int p_73969_2_) {

		buttonList.add(new GuiButton(1, width / 2 - 100, p_73969_1_, I18n.format("menu.singleplayer")));
		buttonList.add(new GuiButton(2, width / 2 - 100, p_73969_1_ + p_73969_2_, I18n.format("menu.multiplayer")));
		realmsButton = addButton(new GuiButton(14, width / 2 - 100, p_73969_1_ + p_73969_2_ * 2, I18n.format("menu.online")));
	}

	/**
	 * Adds Demo buttons on Main Menu for players who are playing Demo.
	 */
	private void addDemoButtons(int p_73972_1_, int p_73972_2_) {

		buttonList.add(new GuiButton(11, width / 2 - 100, p_73972_1_, I18n.format("menu.playdemo")));
		buttonResetDemo = addButton(new GuiButton(12, width / 2 - 100, p_73972_1_ + p_73972_2_, I18n.format("menu.resetdemo")));
		ISaveFormat isaveformat = mc.getSaveLoader();
		WorldInfo worldinfo = isaveformat.getWorldInfo("Demo_World");

		if (worldinfo == null) {
			buttonResetDemo.enabled = false;
		}
	}

	/**
	 * Called by the controls from the buttonList when activated. (Mouse pressed for buttons)
	 */
	protected void actionPerformed(GuiButton button) throws IOException {

		if (button.id == 0) {
			mc.displayGuiScreen(new GuiOptions(this, mc.gameSettings));
		}

		if (button.id == 5) {
			mc.displayGuiScreen(new GuiLanguage(this, mc.gameSettings, mc.getLanguageManager()));
		}

		if (button.id == 1) {
			mc.displayGuiScreen(new GuiWorldSelection(this));
		}

		if (button.id == 2) {
			mc.displayGuiScreen(new GuiMultiplayer(this));
		}

		if (button.id == 14 && realmsButton.visible) {
			switchToRealms();
		}

		if (button.id == 4) {
			mc.shutdown();
		}

		if (button.id == 11) {
			mc.launchIntegratedServer("Demo_World", "Demo_World", WorldServerDemo.DEMO_WORLD_SETTINGS);
		}

		if (button.id == 12) {
			ISaveFormat isaveformat = mc.getSaveLoader();
			WorldInfo worldinfo = isaveformat.getWorldInfo("Demo_World");

			if (worldinfo != null) {
				mc.displayGuiScreen(new GuiYesNo(this, I18n.format("selectWorld.deleteQuestion"), "'" + worldinfo.getWorldName() + "' " + I18n.format("selectWorld.deleteWarning"), I18n.format("selectWorld.deleteButton"), I18n.format("gui.cancel"), 12));
			}
		}
	}

	private void switchToRealms() {

		RealmsBridge realmsbridge = new RealmsBridge();
		realmsbridge.switchToRealms(this);
	}

	public void confirmClicked(boolean result, int id) {

		if (result && id == 12) {
			ISaveFormat isaveformat = mc.getSaveLoader();
			isaveformat.flushCache();
			isaveformat.deleteWorldDirectory("Demo_World");
			mc.displayGuiScreen(this);
		} else if (id == 12) {
			mc.displayGuiScreen(this);
		} else if (id == 13) {
			if (result) {
				try {
					Class<?> oclass = Class.forName("java.awt.Desktop");
					Object object = oclass.getMethod("getDesktop").invoke(null);
					oclass.getMethod("browse", URI.class).invoke(object, new URI(openGLWarningLink));
				} catch (Throwable throwable) {
					LOGGER.error("Couldn't open link", throwable);
				}
			}

			mc.displayGuiScreen(this);
		}
	}

	/**
	 * Draws the main menu panorama
	 */
	private void drawPanorama(int mouseX, int mouseY, float partialTicks) {

		Tessellator tessellator = Tessellator.getInstance();
		BufferBuilder bufferbuilder = tessellator.getBuffer();
		GlStateManager.matrixMode(5889);
		GlStateManager.pushMatrix();
		GlStateManager.loadIdentity();
		Project.gluPerspective(120.0F, 1.0F, 0.05F, 10.0F);
		GlStateManager.matrixMode(5888);
		GlStateManager.pushMatrix();
		GlStateManager.loadIdentity();
		GlStateManager.color(1.0F, 1.0F, 1.0F, 1.0F);
		GlStateManager.rotate(180.0F, 1.0F, 0.0F, 0.0F);
		GlStateManager.rotate(90.0F, 0.0F, 0.0F, 1.0F);
		GlStateManager.enableBlend();
		GlStateManager.disableAlpha();
		GlStateManager.disableCull();
		GlStateManager.depthMask(false);
		GlStateManager.tryBlendFuncSeparate(GlStateManager.SourceFactor.SRC_ALPHA, GlStateManager.DestFactor.ONE_MINUS_SRC_ALPHA, GlStateManager.SourceFactor.ONE, GlStateManager.DestFactor.ZERO);
		int i = 8;

		for (int j = 0; j < 64; ++j) {
			GlStateManager.pushMatrix();
			float f = ((float) (j % 8) / 8.0F - 0.5F) / 64.0F;
			float f1 = ((float) (j / 8) / 8.0F - 0.5F) / 64.0F;
			float f2 = 0.0F;
			GlStateManager.translate(f, f1, 0.0F);
			GlStateManager.rotate(MathHelper.sin(panoramaTimer / 400.0F) * 25.0F + 20.0F, 1.0F, 0.0F, 0.0F);
			GlStateManager.rotate(-panoramaTimer * 0.1F, 0.0F, 1.0F, 0.0F);

			for (int k = 0; k < 6; ++k) {
				GlStateManager.pushMatrix();

				if (k == 1) {
					GlStateManager.rotate(90.0F, 0.0F, 1.0F, 0.0F);
				}

				if (k == 2) {
					GlStateManager.rotate(180.0F, 0.0F, 1.0F, 0.0F);
				}

				if (k == 3) {
					GlStateManager.rotate(-90.0F, 0.0F, 1.0F, 0.0F);
				}

				if (k == 4) {
					GlStateManager.rotate(90.0F, 1.0F, 0.0F, 0.0F);
				}

				if (k == 5) {
					GlStateManager.rotate(-90.0F, 1.0F, 0.0F, 0.0F);
				}

				mc.getTextureManager().bindTexture(TITLE_PANORAMA_PATHS[k]);
				bufferbuilder.begin(7, DefaultVertexFormats.POSITION_TEX_COLOR);
				int l = 255 / (j + 1);
				float f3 = 0.0F;
				bufferbuilder.pos(-1.0D, -1.0D, 1.0D).tex(0.0D, 0.0D).color(255, 255, 255, l).endVertex();
				bufferbuilder.pos(1.0D, -1.0D, 1.0D).tex(1.0D, 0.0D).color(255, 255, 255, l).endVertex();
				bufferbuilder.pos(1.0D, 1.0D, 1.0D).tex(1.0D, 1.0D).color(255, 255, 255, l).endVertex();
				bufferbuilder.pos(-1.0D, 1.0D, 1.0D).tex(0.0D, 1.0D).color(255, 255, 255, l).endVertex();
				tessellator.draw();
				GlStateManager.popMatrix();
			}

			GlStateManager.popMatrix();
			GlStateManager.colorMask(true, true, true, false);
		}

		bufferbuilder.setTranslation(0.0D, 0.0D, 0.0D);
		GlStateManager.colorMask(true, true, true, true);
		GlStateManager.matrixMode(5889);
		GlStateManager.popMatrix();
		GlStateManager.matrixMode(5888);
		GlStateManager.popMatrix();
		GlStateManager.depthMask(true);
		GlStateManager.enableCull();
		GlStateManager.enableDepth();
	}

	/**
	 * Rotate and blurs the skybox view in the main menu
	 */
	private void rotateAndBlurSkybox() {

		mc.getTextureManager().bindTexture(backgroundTexture);
		GlStateManager.glTexParameteri(3553, 10241, 9729);
		GlStateManager.glTexParameteri(3553, 10240, 9729);
		GlStateManager.glCopyTexSubImage2D(3553, 0, 0, 0, 0, 0, 256, 256);
		GlStateManager.enableBlend();
		GlStateManager.tryBlendFuncSeparate(GlStateManager.SourceFactor.SRC_ALPHA, GlStateManager.DestFactor.ONE_MINUS_SRC_ALPHA, GlStateManager.SourceFactor.ONE, GlStateManager.DestFactor.ZERO);
		GlStateManager.colorMask(true, true, true, false);
		Tessellator tessellator = Tessellator.getInstance();
		BufferBuilder bufferbuilder = tessellator.getBuffer();
		bufferbuilder.begin(7, DefaultVertexFormats.POSITION_TEX_COLOR);
		GlStateManager.disableAlpha();
		int i = 3;

		for (int j = 0; j < 3; ++j) {
			float f = 1.0F / (float) (j + 1);
			int k = width;
			int l = height;
			float f1 = (float) (j - 1) / 256.0F;
			bufferbuilder.pos(k, l, zLevel).tex(0.0F + f1, 1.0D).color(1.0F, 1.0F, 1.0F, f).endVertex();
			bufferbuilder.pos(k, 0.0D, zLevel).tex(1.0F + f1, 1.0D).color(1.0F, 1.0F, 1.0F, f).endVertex();
			bufferbuilder.pos(0.0D, 0.0D, zLevel).tex(1.0F + f1, 0.0D).color(1.0F, 1.0F, 1.0F, f).endVertex();
			bufferbuilder.pos(0.0D, l, zLevel).tex(0.0F + f1, 0.0D).color(1.0F, 1.0F, 1.0F, f).endVertex();
		}

		tessellator.draw();
		GlStateManager.enableAlpha();
		GlStateManager.colorMask(true, true, true, true);
	}

	/**
	 * Renders the skybox in the main menu
	 */
	private void renderSkybox(int mouseX, int mouseY, float partialTicks) {

		mc.getFramebuffer().unbindFramebuffer();
		GlStateManager.viewport(0, 0, 256, 256);
		drawPanorama(mouseX, mouseY, partialTicks);
		rotateAndBlurSkybox();
		rotateAndBlurSkybox();
		rotateAndBlurSkybox();
		rotateAndBlurSkybox();
		rotateAndBlurSkybox();
		rotateAndBlurSkybox();
		rotateAndBlurSkybox();
		mc.getFramebuffer().bindFramebuffer(true);
		GlStateManager.viewport(0, 0, mc.displayWidth, mc.displayHeight);
		float f = 120.0F / (float) (width > height ? width : height);
		float f1 = (float) height * f / 256.0F;
		float f2 = (float) width * f / 256.0F;
		int i = width;
		int j = height;
		Tessellator tessellator = Tessellator.getInstance();
		BufferBuilder bufferbuilder = tessellator.getBuffer();
		bufferbuilder.begin(7, DefaultVertexFormats.POSITION_TEX_COLOR);
		bufferbuilder.pos(0.0D, j, zLevel).tex(0.5F - f1, 0.5F + f2).color(1.0F, 1.0F, 1.0F, 1.0F).endVertex();
		bufferbuilder.pos(i, j, zLevel).tex(0.5F - f1, 0.5F - f2).color(1.0F, 1.0F, 1.0F, 1.0F).endVertex();
		bufferbuilder.pos(i, 0.0D, zLevel).tex(0.5F + f1, 0.5F - f2).color(1.0F, 1.0F, 1.0F, 1.0F).endVertex();
		bufferbuilder.pos(0.0D, 0.0D, zLevel).tex(0.5F + f1, 0.5F + f2).color(1.0F, 1.0F, 1.0F, 1.0F).endVertex();
		tessellator.draw();
	}

	/**
	 * Draws the screen and all the components in it.
	 */
	public void drawScreen(int mouseX, int mouseY, float partialTicks) {

		panoramaTimer += partialTicks;
		GlStateManager.disableAlpha();
		renderSkybox(mouseX, mouseY, partialTicks);
		GlStateManager.enableAlpha();
		int i = 274;
		int j = width / 2 - 137;
		int k = 30;
		drawGradientRect(0, 0, width, height, -2130706433, 16777215);
		drawGradientRect(0, 0, width, height, 0, Integer.MIN_VALUE);
		mc.getTextureManager().bindTexture(MINECRAFT_TITLE_TEXTURES);
		GlStateManager.color(1.0F, 1.0F, 1.0F, 1.0F);

		if ((double) minceraftRoll < 1.0E-4D) {
			drawTexturedModalRect(j, 30, 0, 0, 99, 44);
			drawTexturedModalRect(j + 99, 30, 129, 0, 27, 44);
			drawTexturedModalRect(j + 99 + 26, 30, 126, 0, 3, 44);
			drawTexturedModalRect(j + 99 + 26 + 3, 30, 99, 0, 26, 44);
			drawTexturedModalRect(j + 155, 30, 0, 45, 155, 44);
		} else {
			drawTexturedModalRect(j, 30, 0, 0, 155, 44);
			drawTexturedModalRect(j + 155, 30, 0, 45, 155, 44);
		}

		mc.getTextureManager().bindTexture(field_194400_H);
		drawModalRectWithCustomSizedTexture(j + 88, 67, 0.0F, 0.0F, 98, 14, 128.0F, 16.0F);
		GlStateManager.pushMatrix();
		GlStateManager.translate((float) (width / 2 + 90), 70.0F, 0.0F);
		GlStateManager.rotate(-20.0F, 0.0F, 0.0F, 1.0F);
		float f = 1.8F - MathHelper.abs(MathHelper.sin((float) (Minecraft.getSystemTime() % 1000L) / 1000.0F * ((float) Math.PI * 2F)) * 0.1F);
		f = f * 100.0F / (float) (fontRenderer.getStringWidth(splashText) + 32);
		GlStateManager.scale(f, f, f);
		drawCenteredString(fontRenderer, splashText, 0, -8, -256);
		GlStateManager.popMatrix();
		String s = "Minecraft 1.12.2";

		if (mc.isDemo()) {
			s = s + " Demo";
		} else {
			s = s + ("release".equalsIgnoreCase(mc.getVersionType()) ? "" : "/" + mc.getVersionType());
		}

		drawString(fontRenderer, s, 2, height - 10, -1);
		drawString(fontRenderer, "Copyright Mojang AB. Do not distribute!", widthCopyrightRest, height - 10, -1);

		if (mouseX > widthCopyrightRest && mouseX < widthCopyrightRest + widthCopyright && mouseY > height - 10 && mouseY < height && Mouse.isInsideWindow()) {
			drawRect(widthCopyrightRest, height - 1, widthCopyrightRest + widthCopyright, height, -1);
		}

		if (openGLWarning1 != null && !openGLWarning1.isEmpty()) {
			drawRect(openGLWarningX1 - 2, openGLWarningY1 - 2, openGLWarningX2 + 2, openGLWarningY2 - 1, 1428160512);
			drawString(fontRenderer, openGLWarning1, openGLWarningX1, openGLWarningY1, -1);
			drawString(fontRenderer, openGLWarning2, (width - openGLWarning2Width) / 2, (buttonList.get(0)).y - 12, -1);
		}

		super.drawScreen(mouseX, mouseY, partialTicks);

		if (areRealmsNotificationsEnabled()) {
			realmsNotification.drawScreen(mouseX, mouseY, partialTicks);
		}
	}

	/**
	 * Called when the mouse is clicked. Args : mouseX, mouseY, clickedButton
	 */
	protected void mouseClicked(int mouseX, int mouseY, int mouseButton) throws IOException {

		super.mouseClicked(mouseX, mouseY, mouseButton);

		synchronized (threadLock) {
			if (!openGLWarning1.isEmpty() && !StringUtils.isNullOrEmpty(openGLWarningLink) && mouseX >= openGLWarningX1 && mouseX <= openGLWarningX2 && mouseY >= openGLWarningY1 && mouseY <= openGLWarningY2) {
				GuiConfirmOpenLink guiconfirmopenlink = new GuiConfirmOpenLink(this, openGLWarningLink, 13, true);
				guiconfirmopenlink.disableSecurityWarning();
				mc.displayGuiScreen(guiconfirmopenlink);
			}
		}

		if (areRealmsNotificationsEnabled()) {
			realmsNotification.mouseClicked(mouseX, mouseY, mouseButton);
		}

		if (mouseX > widthCopyrightRest && mouseX < widthCopyrightRest + widthCopyright && mouseY > height - 10 && mouseY < height) {
			mc.displayGuiScreen(new GuiWinGame(false, Runnables.doNothing()));
		}
	}

	/**
	 * Called when the screen is unloaded. Used to disable keyboard repeat events
	 */
	public void onGuiClosed() {

		if (realmsNotification != null) {
			realmsNotification.onGuiClosed();
		}
	}

}
